
$FIRST_NUM = 3
$SECOND_NUM = 5
$THIRD_NUM = 2
$FOURTH_NUM = 1
$FITH_NUM = 4

$SUM = $FIRST_NUM + $SECOND_NUM - $THIRD_NUM * $FOURTH_NUM / $FITH_NUM
Write-Host $SUM
Write-Host $FIRST_NUM "+" $SECOND_NUM "-" $THIRD_NUM "*" $FOURTH_NUM "/" $FITH_NUM "=" $SUM